nodeLinker: node-modules
enableGlobalCache: true

logFilters:
  - code: YN0013
    level: discard

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
